# Welcome to Jekyll!

# Select a theme
theme: jekyll-theme-minimal

# Site-wide title (appears in browser tab)
title: Shuqi Song

# Site-wide description
description: PhD Student in Statistics at the University of South Carolina.

# google_analytics: G-6WFBERR0W2

# Blog/article URLs
permalink: /:categories/:year/:month/:day/:title/

# Keep generated files out of source control noise
exclude:
  - README.md
